### ISSUE TITLE
no rtv smx nor any configs.

### ISSUE THREAD

**Issue by bingussssbaldcat** [tilgep/Mapchooser-Unlimited#1]
hello mate, you have no smx file, nor any cfgs (like the ones in other mapchoosers) pls add and updated cfg.

**Comment by tilgep** [comment]
All that information is in the readme, and if you can't compile plugins for yourself there are tutorials on the alliedmodders forums I'm sure.

**Comment by bingussssbaldcat** [comment]
> All that information is in the readme, and if you can't compile plugins for yourself there are tutorials on the alliedmodders forums I'm sure.

i know how to compile the plugin, u said "For RTV to work, you must change RTV to use the mapchooser_unlimited include file (Any natives used should work)" so u saying i use sm default rtv and compile it with mapchoosers includes?
